# Fields that end up in the mod's manifest.
[manifest]
id = "unlock_mystery_menu"
version = "1.0.0"
display_name = "Unlock Mystery Menu"
description =  "Enables and Unlocks everything on the mystery menu on the main menu by default. Does not affect any save files."
short_description = "Unlocks the mystery menu by default."
authors = [ "Fewffwa" ]
game_id = "dk64"
minimum_recomp_version = "1.0.0"

# Inputs to the mod tool.
[inputs]
elf_path = "build/mod.elf"
mod_filename = "unlock_mystery_menu"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]